# fly.toml app configuration file for uni-midterm-rest-api
app = 'uni-midterm-rest-api'
primary_region = 'ams'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8080'  # Matches Dockerfile

[http_service]
  internal_port = 8080  # Matches Dockerfile
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/staticfiles'  # Matches Django STATIC_ROOT
  url_prefix = '/static/'

[mounts]
source = "app_data"
destination = "/data"
