# Generated by Django 5.1.4 on 2024-12-16 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndRestAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proficiencyrace',
            name='subrace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proficiencies', to='dndRestAPI.subrace'),
        ),
        migrations.AlterField(
            model_name='proficiencyrace',
            name='proficiency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races_and_subraces', to='dndRestAPI.proficiency'),
        ),
        migrations.AlterField(
            model_name='proficiencyrace',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proficiencies', to='dndRestAPI.race'),
        ),
    ]
